import DAccess from "./components/DAccess.vue";
import DAlert from "./components/DAlert.vue";
import DApp from "./components/DApp.vue";
import DAutocomplete from "./components/DAutocomplete.vue";
import DAutocompleteChipSet from "./components/DAutocompleteChipSet.vue";
import DBlurHash from "./components/DBlurHash.vue";
import DBlurImg from "./components/DBlurImg.vue";
import DBottomBar from "./components/DBottomBar.vue";
import DBreadcrumbs from "./components/DBreadcrumbs.vue";
import DBtn from "./components/DBtn.vue";
import DBtnCancel from "./components/DBtnCancel.vue";
import DBtnCheckbox from "./components/DBtnCheckbox.vue";
import DBtnDrawer from "./components/DBtnDrawer.vue";
import DBtnEdit from "./components/DBtnEdit.vue";
import DBtnFile from "./components/DBtnFile.vue";
import DBtnLatch from "./components/DBtnLatch.vue";
import DBtnLink from "./components/DBtnLink.vue";
import DBtnSave from "./components/DBtnSave.vue";
import DBtnRemove from "./components/DBtnRemove.vue";
import DBtnToggle from "./components/DBtnToggle.vue";
import DCard from "./components/DCard.vue";
import DCarousel from "./components/DCarousel.vue";
import DCarouselItem from "./components/DCarouselItem.vue";
import DCheckbox from "./components/DCheckbox.vue";
import DChip from "./components/DChip.vue";
import DChipGroup from "./components/DChipGroup.vue";
import DChipSet from "./components/DChipSet.vue";
import DCircle from "./components/DCircle.vue";
import DContainer from "./components/DContainer.vue";
import DCreateEntityBtn from "./components/DCreateEntityBtn.vue";
import DCreateEntityForm from "./components/DCreateEntityForm.vue";
import DDatePicker from "./components/DDatePicker.vue";
import DDateTimePicker from "./components/DDateTimePicker.vue";
import DDataList from "./components/DDataList.vue";
import DDataTable from "./components/DDataTable.vue";
import DDraggable from "./components/DDraggable.vue";
import DDraggableDataList from "./components/DDraggableDataList.vue";
import DDraggableDataRow from "./components/DDraggableDataRow.vue";
import DDraggableDataTable from "./components/DDraggableDataTable.vue";
import DDraggableList from "./components/DDraggableList.vue";
import DDraggableTile from "./components/DDraggableTile.vue";
import DDroppableBreadcrumbs from "./components/DDroppableBreadcrumbs.vue";
import DEditor from "./components/DEditor.vue";
import DExpansionPanel from "./components/DExpansionPanel.vue";
import DExpansionPanelContent from "./components/DExpansionPanelContent.vue";
import DExpansionPanelHeader from "./components/DExpansionPanelHeader.vue";
import DExpansionPanels from "./components/DExpansionPanels.vue";
import DGrid from "./components/DGrid.vue";
import DIcon from "./components/DIcon.vue";
import DIconBtn from "./components/DIconBtn.vue";
import DIconAutocomplete from "./components/DIconAutocomplete.vue";
import DImg from "./components/DImg.vue";
import DImgCarousel from "./components/DImgCarousel.vue";
import DInputAutocomplete from "./components/DInputAutocomplete.vue";
import DLightTabs from "./components/DLightTabs.vue";
import DLink from "./components/DLink.vue";
import DList from "./components/DList.vue";
import DListItem from "./components/DListItem.vue";
import DListItemGroup from "./components/DListItemGroup.vue";
import DMenu from "./components/DMenu.vue";
import DMenuBtn from "./components/DMenuBtn.vue";
import DOutlinedImg from "./components/DOutlinedImg.vue";
import DOutlinedBlurImg from "./components/DOutlinedBlurImg.vue";
import DOutlinedBlurImgBtn from "./components/DOutlinedBlurImgBtn.vue";
import DPasswordInput from "./components/DPasswordInput.vue";
import DRightDrawer from "./components/DRightDrawer.vue";
import DSearchInput from "./components/DSearchInput.vue";
import DSelect from "./components/DSelect.vue";
import DSimpleCheckbox from "./components/DSimpleCheckbox.vue";
import DSheet from "./components/DSheet.vue";
import DSlider from "./components/DSlider.vue";
import DSpinner from "./components/DSpinner.vue";
import DSubTitle from "./components/DSubTitle.vue";
import DSwitch from "./components/DSwitch.vue";
import DSwitchGrid from "./components/DSwitchGrid.vue";
import DModulableTabs from "./components/DModulableTabs.vue";
import DTabs from "./components/DTabs.vue";
import DTab from "./components/DTab.vue";
import DTabsItems from "./components/DTabsItems.vue";
import DTabItem from "./components/DTabItem.vue";
import DTextarea from "./components/DTextarea.vue";
import DTextField from "./components/DTextField.vue";
import DText from "./components/DText.vue";
import DTile from "./components/DTile.vue";
import DTitle from "./components/DTitle.vue";
import DToggle from "./components/DToggle.vue";
import DToggleSet from "./components/DToggleSet.vue";
import DSimpleDialog from "./components/DSimpleDialog.vue";
import DValidationBar from "./components/DValidationBar.vue";

import DBaseConfiguration from "./components/dashboard/DBaseConfiguration.vue";
import DBaseWidget from "./components/dashboard/DBaseWidget.vue";
import DDashboard from "./components/dashboard/DDashboard.vue";
import DDashboardCase from "./components/dashboard/DDashboardCase.vue";

import AlertLoader from "./components/loaders/AlertLoader.vue";
import DashboardLoader from "./components/loaders/DashboardLoader.vue";
import DeviceLoader from "./components/loaders/DeviceLoader.vue";
import DListLoader from "./components/loaders/DListLoader.vue";
import DrawerLoader from "./components/loaders/DrawerLoader.vue";
import DumbListLoader from "./components/loaders/DumbListLoader.vue";
import LocationLoader from "./components/loaders/LocationLoader.vue";
import MapLoader from "./components/loaders/MapLoader.vue";
import OrganisationLoader from "./components/loaders/OrganisationLoader.vue";
import ScenarioCreationLoader from "./components/loaders/ScenarioCreationLoader.vue";
import ScenarioLoader from "./components/loaders/ScenarioLoader.vue";
import StatisticsDeviceLoader from "./components/loaders/StatisticsDeviceLoader.vue";
import StatisticsLoader from "./components/loaders/StatisticsLoader.vue";
import StatisticTemplateLoader from "./components/loaders/StatisticTemplateLoader.vue";

import { Flags } from "./flags";
import { Icons } from "./icons";
import { Colors } from "./colors";

import * as Models from "./models";

import "./style.css";
import '@fontsource/open-sans'
import '@fontsource/montserrat'

const Shards = {
  install(vue: any, options: any) {
    vue.prototype.$color = function (colorKey: string) {
      return this.$vuetify.theme.currentTheme[colorKey]
    };

    vue.component("d-access", DAccess);
    vue.component("d-alert", DAlert);
    vue.component("d-app", DApp);
    vue.component("d-autocomplete", DAutocomplete);
    vue.component("d-autocomplete-chip-set", DAutocompleteChipSet)
    vue.component("d-blur-hash", DBlurHash);
    vue.component("d-blur-img", DBlurImg);
    vue.component("d-bottom-bar", DBottomBar);
    vue.component("d-breadcrumbs", DBreadcrumbs);
    vue.component("d-btn", DBtn);
    vue.component("d-btn-cancel", DBtnCancel);
    vue.component("d-btn-checkbox", DBtnCheckbox);
    vue.component("d-btn-drawer", DBtnDrawer);
    vue.component("d-btn-edit", DBtnEdit);
    vue.component("d-btn-file", DBtnFile);
    vue.component("d-btn-link", DBtnLink);
    vue.component("d-btn-latch", DBtnLatch);
    vue.component("d-btn-remove", DBtnRemove);
    vue.component("d-btn-save", DBtnSave);
    vue.component("d-btn-toggle", DBtnToggle);
    vue.component("d-card", DCard);
    vue.component("d-carousel", DCarousel);
    vue.component("d-carousel-item", DCarouselItem);
    vue.component("d-checkbox", DCheckbox);
    vue.component("d-chip", DChip);
    vue.component("d-chip-set", DChipSet);
    vue.component("d-chip-group", DChipGroup);
    vue.component("d-circle", DCircle);
    vue.component("d-container", DContainer);
    vue.component("d-create-entity-btn", DCreateEntityBtn);
    vue.component("d-create-entity-form", DCreateEntityForm);
    vue.component("d-data-list", DDataList);
    vue.component("d-data-table", DDataTable);
    vue.component("d-date-picker", DDatePicker);
    vue.component("d-date-time-picker", DDateTimePicker);
    vue.component("d-draggable", DDraggable);
    vue.component("d-draggable-data-list", DDraggableDataList);
    vue.component("d-draggable-data-row", DDraggableDataRow);
    vue.component("d-draggable-data-table", DDraggableDataTable);
    vue.component("d-draggable-list", DDraggableList);
    vue.component("d-draggable-tile", DDraggableTile);
    vue.component("d-droppable-breadcrumbs", DDroppableBreadcrumbs);
    vue.component("d-editor", DEditor);
    vue.component("d-expansion-panel", DExpansionPanel);
    vue.component("d-expansion-panel-content", DExpansionPanelContent);
    vue.component("d-expansion-panel-header", DExpansionPanelHeader);
    vue.component("d-expansion-panels", DExpansionPanels);
    vue.component("d-grid", DGrid);
    vue.component("d-icon", DIcon);
    vue.component("d-icon-btn", DIconBtn);
    vue.component("d-icon-autocomplete", DIconAutocomplete);
    vue.component("d-img", DImg);
    vue.component("d-img-carousel", DImgCarousel);
    vue.component("d-input-autocomplete", DInputAutocomplete);
    vue.component("d-light-tabs", DLightTabs);
    vue.component("d-link", DLink);
    vue.component("d-list", DList);
    vue.component("d-list-item", DListItem);
    vue.component("d-list-item-group", DListItemGroup);
    vue.component("d-menu", DMenu);
    vue.component("d-menu-btn", DMenuBtn);
    vue.component("d-outlined-img", DOutlinedImg);
    vue.component("d-outlined-blur-img", DOutlinedBlurImg);
    vue.component("d-outlined-blur-img-btn", DOutlinedBlurImgBtn);
    vue.component("d-password-input", DPasswordInput);
    vue.component("d-right-drawer", DRightDrawer);
    vue.component("d-search-input", DSearchInput);
    vue.component("d-select", DSelect);
    vue.component("d-sheet", DSheet);
    vue.component("d-simple-checkbox", DSimpleCheckbox);
    vue.component("d-slider", DSlider);
    vue.component("d-spinner", DSpinner);
    vue.component("d-sub-title", DSubTitle);
    vue.component("d-switch", DSwitch);
    vue.component("d-switch-grid", DSwitchGrid);
    vue.component("d-modulable-tabs", DModulableTabs);
    vue.component("d-tabs", DTabs);
    vue.component("d-tab", DTab);
    vue.component("d-tabs-items", DTabsItems);
    vue.component("d-tab-item", DTabItem);
    vue.component("d-textarea", DTextarea);
    vue.component("d-text-field", DTextField);
    vue.component("d-text", DText);
    vue.component("d-tile", DTile);
    vue.component("d-title", DTitle);
    vue.component("d-toggle", DToggle);
    vue.component("d-toggle-set", DToggleSet);
    vue.component("d-simple-dialog", DSimpleDialog);
    vue.component("d-validation-bar", DValidationBar);

    vue.component("d-base-configuration", DBaseConfiguration);
    vue.component("d-base-widget", DBaseWidget);
    vue.component("d-dashboard", DDashboard);
    vue.component("d-dashboard-case", DDashboardCase);

    vue.component("alert-loader", AlertLoader);
    vue.component("dashboard-loader", DashboardLoader);
    vue.component("device-loader", DeviceLoader);
    vue.component("d-list-loader", DListLoader);
    vue.component("drawer-loader", DrawerLoader);
    vue.component("dumb-list-loader", DumbListLoader);
    vue.component("location-loader", LocationLoader);
    vue.component("map-loader", MapLoader);
    vue.component("organisation-loader", OrganisationLoader);
    vue.component("scenario-creation-loader", ScenarioCreationLoader);
    vue.component("scenario-loader", ScenarioLoader);
    vue.component("statistics-device-loader", StatisticsDeviceLoader);
    vue.component("statistics-loader", StatisticsLoader);
    vue.component("statistic-template-loader", StatisticTemplateLoader);
  }
};

export { Shards, Flags, Icons, Colors, Models };