name: Publish Package to npmjs
on:
  push:
    tags: 
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      # Checking out repository
      - uses: actions/checkout@v2

      # Setting .npmrc file up to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          # User or organization
          scope: '@dative-gpi'

      # Publishing with tag name as version
      - env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd src
          yarn publish --new-version ${{ github.ref_name }}